# Generated by Django 5.2.17 on 2026-09-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=15)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_address', models.TextField(blank=True)),
                ('products', models.JSONField(default=list)),
                ('total_copies', models.PositiveIntegerField(default=0)),
                ('paper_size', models.CharField(blank=True, max_length=50)),
                ('printing_color', models.CharField(blank=True, max_length=50)),
                ('printing_page', models.CharField(blank=True, max_length=50)),
                ('printing_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('design_required', models.CharField(default='no', max_length=10)),
                ('design_page', models.CharField(blank=True, max_length=50)),
                ('design_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lamination', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('embossing', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('card_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
