# Generated by Django 5.2.17 on 2026-09-08 11:57

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_companysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='default_gst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='design_charges',
            field=models.JSONField(default=users.models.default_design_charges),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='embossing_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='invoice_footer',
            field=models.TextField(default='Thank you for choosing GP Prints!'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='invoice_prefix',
            field=models.CharField(default='GP-', max_length=20),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='lamination_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='printing_charges',
            field=models.JSONField(default=users.models.default_printing_charges),
        ),
    ]
