# Generated by Django 5.2.17 on 2026-09-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_companysettings_default_gst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='multicolor_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
