# Generated by Django 5.2.17 on 2026-09-10 15:21

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_bill_multicolor_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='multicolor_charges',
            field=models.JSONField(default=users.models.default_multicolor_charges),
        ),
    ]
