# Generated by Django 5.2.17 on 2026-09-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_seed_other_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='other_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
