# Generated by Django 5.2.17 on 2026-09-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_bill_other_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrule',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='unit',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
